package com.ultra.megamod.feature.relics;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Auto-generated by scripts/generate_relic_spells.py - Phase G.1.
 * Maps each relic item registry ID to the list of SpellEngine spell IDs for its abilities.
 * RelicRegistry uses this to attach a SpellContainer data component.
 * Also exposes per-spell metadata (ability display name, required relic level)
 * used by the level-gate cast predicate.
 */
public final class RelicSpellAssignments {
    private RelicSpellAssignments() {}

    public static final Map<String, List<String>> SPELLS;
    /** spell id -> (ability display name, required level) */
    public static final Map<String, SpellMeta> META;

    public record SpellMeta(String abilityName, int requiredLevel) {}

    static {
        Map<String, List<String>> spells = new HashMap<>();
        spells.put("megamod:abyssal_cape", List.of("megamod:relic_abyssal_cape_void_walker", "megamod:relic_abyssal_cape_blink", "megamod:relic_abyssal_cape_void_rift"));
        spells.put("megamod:alchemists_sash", List.of("megamod:relic_alchemists_sash_potion_mastery", "megamod:relic_alchemists_sash_transmute", "megamod:relic_alchemists_sash_volatile_mix"));
        spells.put("megamod:amphibian_boot", List.of("megamod:relic_amphibian_boot_swim_speed", "megamod:relic_amphibian_boot_frog_jump"));
        spells.put("megamod:aqua_walker", List.of("megamod:relic_aqua_walker_water_walk", "megamod:relic_aqua_walker_ripple"));
        spells.put("megamod:arcane_gauntlet", List.of("megamod:relic_arcane_gauntlet_mana_shield", "megamod:relic_arcane_gauntlet_arcane_bolt", "megamod:relic_arcane_gauntlet_spellweave"));
        spells.put("megamod:arrow_quiver", List.of("megamod:relic_arrow_quiver_receptacle", "megamod:relic_arrow_quiver_leap", "megamod:relic_arrow_quiver_agility", "megamod:relic_arrow_quiver_rain"));
        spells.put("megamod:ashen_diadem", List.of("megamod:relic_ashen_diadem_ember_sight", "megamod:relic_ashen_diadem_infernal_command", "megamod:relic_ashen_diadem_pyroclasm"));
        spells.put("megamod:bastion_ring", List.of("megamod:relic_bastion_ring_piglin_peace", "megamod:relic_bastion_ring_barter_bonus", "megamod:relic_bastion_ring_gilded_strike"));
        spells.put("megamod:blazing_flask", List.of("megamod:relic_blazing_flask_fire_ball", "megamod:relic_blazing_flask_jetpack"));
        spells.put("megamod:bloodstone_choker", List.of("megamod:relic_bloodstone_choker_bloodlust", "megamod:relic_bloodstone_choker_blood_price", "megamod:relic_bloodstone_choker_sanguine_feast"));
        spells.put("megamod:chorus_inhibitor", List.of("megamod:relic_chorus_inhibitor_anchor", "megamod:relic_chorus_inhibitor_displace", "megamod:relic_chorus_inhibitor_void_grip"));
        spells.put("megamod:chrono_glove", List.of("megamod:relic_chrono_glove_temporal_flux", "megamod:relic_chrono_glove_time_snap", "megamod:relic_chrono_glove_stasis_field"));
        spells.put("megamod:drowned_belt", List.of("megamod:relic_drowned_belt_depths", "megamod:relic_drowned_belt_pressure", "megamod:relic_drowned_belt_anchor"));
        spells.put("megamod:elytra_booster", List.of("megamod:relic_elytra_booster_acceleration", "megamod:relic_elytra_booster_fuel_efficiency", "megamod:relic_elytra_booster_glide"));
        spells.put("megamod:emberstone_band", List.of("megamod:relic_emberstone_band_warm_aura", "megamod:relic_emberstone_band_fire_snap", "megamod:relic_emberstone_band_combustion"));
        spells.put("megamod:ender_hand", List.of("megamod:relic_ender_hand_enderman_peace", "megamod:relic_ender_hand_teleport_swap"));
        spells.put("megamod:frostfire_pendant", List.of("megamod:relic_frostfire_pendant_equilibrium", "megamod:relic_frostfire_pendant_frostfire_bolt", "megamod:relic_frostfire_pendant_elemental_storm"));
        spells.put("megamod:frostweave_veil", List.of("megamod:relic_frostweave_veil_cold_breath", "megamod:relic_frostweave_veil_frozen_gaze", "megamod:relic_frostweave_veil_blizzard_aura"));
        spells.put("megamod:gravestone_ring", List.of("megamod:relic_gravestone_ring_death_ward", "megamod:relic_gravestone_ring_life_tap", "megamod:relic_gravestone_ring_undying_resolve"));
        spells.put("megamod:guardians_girdle", List.of("megamod:relic_guardians_girdle_fortitude", "megamod:relic_guardians_girdle_brace", "megamod:relic_guardians_girdle_stalwart_stand"));
        spells.put("megamod:holy_locket", List.of("megamod:relic_holy_locket_steal", "megamod:relic_holy_locket_purify", "megamod:relic_holy_locket_sanctify"));
        spells.put("megamod:horse_flute", List.of("megamod:relic_horse_flute_store", "megamod:relic_horse_flute_release"));
        spells.put("megamod:hunter_belt", List.of("megamod:relic_hunter_belt_tracker", "megamod:relic_hunter_belt_harvest", "megamod:relic_hunter_belt_predator"));
        spells.put("megamod:ice_breaker", List.of("megamod:relic_ice_breaker_stomp", "megamod:relic_ice_breaker_frost_thorns"));
        spells.put("megamod:ice_skates", List.of("megamod:relic_ice_skates_glide", "megamod:relic_ice_skates_ice_trail"));
        spells.put("megamod:infinity_ham", List.of("megamod:relic_infinity_ham_feast", "megamod:relic_infinity_ham_alchemy"));
        spells.put("megamod:iron_fist", List.of("megamod:relic_iron_fist_heavy_blows", "megamod:relic_iron_fist_uppercut", "megamod:relic_iron_fist_ground_pound"));
        spells.put("megamod:jellyfish_necklace", List.of("megamod:relic_jellyfish_necklace_unsinkable", "megamod:relic_jellyfish_necklace_shock", "megamod:relic_jellyfish_necklace_paralysis"));
        spells.put("megamod:leather_belt", List.of("megamod:relic_leather_belt_toughness", "megamod:relic_leather_belt_endurance", "megamod:relic_leather_belt_carry_weight"));
        spells.put("megamod:lodestone_magnet", List.of("megamod:relic_lodestone_magnet_attraction", "megamod:relic_lodestone_magnet_selective_pull", "megamod:relic_lodestone_magnet_expanded_range", "megamod:relic_lodestone_magnet_vacuum"));
        spells.put("megamod:lunar_crown", List.of("megamod:relic_lunar_crown_lunar_glow", "megamod:relic_lunar_crown_moonbeam", "megamod:relic_lunar_crown_eclipse"));
        spells.put("megamod:magic_mirror", List.of("megamod:relic_magic_mirror_recall", "megamod:relic_magic_mirror_bed_recall"));
        spells.put("megamod:magma_walker", List.of("megamod:relic_magma_walker_heat_shield", "megamod:relic_magma_walker_lava_walk", "megamod:relic_magma_walker_eruption"));
        spells.put("megamod:mending_chalice", List.of("megamod:relic_mending_chalice_healing_draught", "megamod:relic_mending_chalice_sanctified_ground"));
        spells.put("megamod:midnight_robe", List.of("megamod:relic_midnight_robe_vanish", "megamod:relic_midnight_robe_backstab", "megamod:relic_midnight_robe_shadow_step"));
        spells.put("megamod:phoenix_mantle", List.of("megamod:relic_phoenix_mantle_fireborn", "megamod:relic_phoenix_mantle_rebirth", "megamod:relic_phoenix_mantle_inferno_wings"));
        spells.put("megamod:plague_grasp", List.of("megamod:relic_plague_grasp_venomous_touch", "megamod:relic_plague_grasp_wither_grip", "megamod:relic_plague_grasp_plague_wave"));
        spells.put("megamod:rage_glove", List.of("megamod:relic_rage_glove_fury", "megamod:relic_rage_glove_bare_knuckle", "megamod:relic_rage_glove_berserk"));
        spells.put("megamod:reflection_necklace", List.of("megamod:relic_reflection_necklace_absorb", "megamod:relic_reflection_necklace_explode"));
        spells.put("megamod:roller_skates", List.of("megamod:relic_roller_skates_momentum", "megamod:relic_roller_skates_double_jump"));
        spells.put("megamod:sandwalker_treads", List.of("megamod:relic_sandwalker_treads_desert_born", "megamod:relic_sandwalker_treads_quicksand", "megamod:relic_sandwalker_treads_sandstorm"));
        spells.put("megamod:serpent_belt", List.of("megamod:relic_serpent_belt_constrictor", "megamod:relic_serpent_belt_venom_spit", "megamod:relic_serpent_belt_coil_strike"));
        spells.put("megamod:shadow_glaive", List.of("megamod:relic_shadow_glaive_throw", "megamod:relic_shadow_glaive_saw_mode"));
        spells.put("megamod:solar_crown", List.of("megamod:relic_solar_crown_solar_warmth", "megamod:relic_solar_crown_sunfire", "megamod:relic_solar_crown_radiance"));
        spells.put("megamod:space_dissector", List.of("megamod:relic_space_dissector_mark", "megamod:relic_space_dissector_warp"));
        spells.put("megamod:spore_sack", List.of("megamod:relic_spore_sack_spore_shot", "megamod:relic_spore_sack_cloud"));
        spells.put("megamod:stormband", List.of("megamod:relic_stormband_charged_steps", "megamod:relic_stormband_arc_discharge", "megamod:relic_stormband_galvanic_surge"));
        spells.put("megamod:stormcaller_circlet", List.of("megamod:relic_stormcaller_circlet_static_field", "megamod:relic_stormcaller_circlet_thunder_strike", "megamod:relic_stormcaller_circlet_tempest_aura"));
        spells.put("megamod:stormstrider_boots", List.of("megamod:relic_stormstrider_boots_lightning_step", "megamod:relic_stormstrider_boots_thunder_leap"));
        spells.put("megamod:sunforged_bracer", List.of("megamod:relic_sunforged_bracer_blessed_strikes", "megamod:relic_sunforged_bracer_purifying_touch", "megamod:relic_sunforged_bracer_divine_smite"));
        spells.put("megamod:thornweave_glove", List.of("megamod:relic_thornweave_glove_thorned_grasp", "megamod:relic_thornweave_glove_vine_lash", "megamod:relic_thornweave_glove_entangle"));
        spells.put("megamod:thunderhorn", List.of("megamod:relic_thunderhorn_war_cry", "megamod:relic_thunderhorn_sonic_boom"));
        spells.put("megamod:tidekeeper_amulet", List.of("megamod:relic_tidekeeper_amulet_aquatic_grace", "megamod:relic_tidekeeper_amulet_tidal_wave", "megamod:relic_tidekeeper_amulet_whirlpool"));
        spells.put("megamod:verdant_mask", List.of("megamod:relic_verdant_mask_pollen_shield", "megamod:relic_verdant_mask_thorned_veil", "megamod:relic_verdant_mask_blossom_burst"));
        spells.put("megamod:verdant_signet", List.of("megamod:relic_verdant_signet_nature_s_blessing", "megamod:relic_verdant_signet_growth_surge", "megamod:relic_verdant_signet_bloom_shield"));
        spells.put("megamod:void_lantern", List.of("megamod:relic_void_lantern_dark_beacon", "megamod:relic_void_lantern_dimensional_tear"));
        spells.put("megamod:wardens_visor", List.of("megamod:relic_wardens_visor_tremor_sense", "megamod:relic_wardens_visor_sonic_pulse", "megamod:relic_wardens_visor_sculk_shroud"));
        spells.put("megamod:windrunner_cloak", List.of("megamod:relic_windrunner_cloak_tailwind", "megamod:relic_windrunner_cloak_gust", "megamod:relic_windrunner_cloak_dash"));
        spells.put("megamod:wool_mitten", List.of("megamod:relic_wool_mitten_warmth", "megamod:relic_wool_mitten_comfort", "megamod:relic_wool_mitten_cozy"));
        spells.put("megamod:wraith_crown", List.of("megamod:relic_wraith_crown_ethereal_sight", "megamod:relic_wraith_crown_soul_siphon", "megamod:relic_wraith_crown_phantom_form"));
        SPELLS = Map.copyOf(spells);

        Map<String, SpellMeta> meta = new HashMap<>();
        meta.put("megamod:relic_abyssal_cape_void_walker", new SpellMeta("Void Walker", 1));
        meta.put("megamod:relic_abyssal_cape_blink", new SpellMeta("Blink", 3));
        meta.put("megamod:relic_abyssal_cape_void_rift", new SpellMeta("Void Rift", 7));
        meta.put("megamod:relic_arrow_quiver_receptacle", new SpellMeta("Receptacle", 1));
        meta.put("megamod:relic_arrow_quiver_leap", new SpellMeta("Leap", 3));
        meta.put("megamod:relic_arrow_quiver_agility", new SpellMeta("Agility", 5));
        meta.put("megamod:relic_arrow_quiver_rain", new SpellMeta("Rain", 7));
        meta.put("megamod:relic_elytra_booster_acceleration", new SpellMeta("Acceleration", 1));
        meta.put("megamod:relic_elytra_booster_fuel_efficiency", new SpellMeta("Fuel Efficiency", 3));
        meta.put("megamod:relic_elytra_booster_glide", new SpellMeta("Glide", 5));
        meta.put("megamod:relic_midnight_robe_vanish", new SpellMeta("Vanish", 1));
        meta.put("megamod:relic_midnight_robe_backstab", new SpellMeta("Backstab", 4));
        meta.put("megamod:relic_midnight_robe_shadow_step", new SpellMeta("Shadow Step", 7));
        meta.put("megamod:relic_phoenix_mantle_fireborn", new SpellMeta("Fireborn", 1));
        meta.put("megamod:relic_phoenix_mantle_rebirth", new SpellMeta("Rebirth", 4));
        meta.put("megamod:relic_phoenix_mantle_inferno_wings", new SpellMeta("Inferno Wings", 7));
        meta.put("megamod:relic_windrunner_cloak_tailwind", new SpellMeta("Tailwind", 1));
        meta.put("megamod:relic_windrunner_cloak_gust", new SpellMeta("Gust", 3));
        meta.put("megamod:relic_windrunner_cloak_dash", new SpellMeta("Dash", 6));
        meta.put("megamod:relic_alchemists_sash_potion_mastery", new SpellMeta("Potion Mastery", 1));
        meta.put("megamod:relic_alchemists_sash_transmute", new SpellMeta("Transmute", 4));
        meta.put("megamod:relic_alchemists_sash_volatile_mix", new SpellMeta("Volatile Mix", 7));
        meta.put("megamod:relic_drowned_belt_depths", new SpellMeta("Depths", 1));
        meta.put("megamod:relic_drowned_belt_pressure", new SpellMeta("Pressure", 4));
        meta.put("megamod:relic_drowned_belt_anchor", new SpellMeta("Anchor", 6));
        meta.put("megamod:relic_guardians_girdle_fortitude", new SpellMeta("Fortitude", 1));
        meta.put("megamod:relic_guardians_girdle_brace", new SpellMeta("Brace", 4));
        meta.put("megamod:relic_guardians_girdle_stalwart_stand", new SpellMeta("Stalwart Stand", 7));
        meta.put("megamod:relic_hunter_belt_tracker", new SpellMeta("Tracker", 1));
        meta.put("megamod:relic_hunter_belt_harvest", new SpellMeta("Harvest", 4));
        meta.put("megamod:relic_hunter_belt_predator", new SpellMeta("Predator", 6));
        meta.put("megamod:relic_leather_belt_toughness", new SpellMeta("Toughness", 1));
        meta.put("megamod:relic_leather_belt_endurance", new SpellMeta("Endurance", 3));
        meta.put("megamod:relic_leather_belt_carry_weight", new SpellMeta("Carry Weight", 5));
        meta.put("megamod:relic_lodestone_magnet_attraction", new SpellMeta("Attraction", 1));
        meta.put("megamod:relic_lodestone_magnet_selective_pull", new SpellMeta("Selective Pull", 3));
        meta.put("megamod:relic_lodestone_magnet_expanded_range", new SpellMeta("Expanded Range", 5));
        meta.put("megamod:relic_lodestone_magnet_vacuum", new SpellMeta("Vacuum", 7));
        meta.put("megamod:relic_serpent_belt_constrictor", new SpellMeta("Constrictor", 1));
        meta.put("megamod:relic_serpent_belt_venom_spit", new SpellMeta("Venom Spit", 3));
        meta.put("megamod:relic_serpent_belt_coil_strike", new SpellMeta("Coil Strike", 6));
        meta.put("megamod:relic_frostweave_veil_cold_breath", new SpellMeta("Cold Breath", 1));
        meta.put("megamod:relic_frostweave_veil_frozen_gaze", new SpellMeta("Frozen Gaze", 4));
        meta.put("megamod:relic_frostweave_veil_blizzard_aura", new SpellMeta("Blizzard Aura", 7));
        meta.put("megamod:relic_verdant_mask_pollen_shield", new SpellMeta("Pollen Shield", 1));
        meta.put("megamod:relic_verdant_mask_thorned_veil", new SpellMeta("Thorned Veil", 4));
        meta.put("megamod:relic_verdant_mask_blossom_burst", new SpellMeta("Blossom Burst", 7));
        meta.put("megamod:relic_wardens_visor_tremor_sense", new SpellMeta("Tremor Sense", 1));
        meta.put("megamod:relic_wardens_visor_sonic_pulse", new SpellMeta("Sonic Pulse", 4));
        meta.put("megamod:relic_wardens_visor_sculk_shroud", new SpellMeta("Sculk Shroud", 7));
        meta.put("megamod:relic_amphibian_boot_swim_speed", new SpellMeta("Swim Speed", 1));
        meta.put("megamod:relic_amphibian_boot_frog_jump", new SpellMeta("Frog Jump", 4));
        meta.put("megamod:relic_aqua_walker_water_walk", new SpellMeta("Water Walk", 1));
        meta.put("megamod:relic_aqua_walker_ripple", new SpellMeta("Ripple", 4));
        meta.put("megamod:relic_ice_breaker_stomp", new SpellMeta("Stomp", 1));
        meta.put("megamod:relic_ice_breaker_frost_thorns", new SpellMeta("Frost Thorns", 4));
        meta.put("megamod:relic_ice_skates_glide", new SpellMeta("Glide", 1));
        meta.put("megamod:relic_ice_skates_ice_trail", new SpellMeta("Ice Trail", 4));
        meta.put("megamod:relic_magma_walker_heat_shield", new SpellMeta("Heat Shield", 1));
        meta.put("megamod:relic_magma_walker_lava_walk", new SpellMeta("Lava Walk", 3));
        meta.put("megamod:relic_magma_walker_eruption", new SpellMeta("Eruption", 6));
        meta.put("megamod:relic_roller_skates_momentum", new SpellMeta("Momentum", 1));
        meta.put("megamod:relic_roller_skates_double_jump", new SpellMeta("Double Jump", 4));
        meta.put("megamod:relic_sandwalker_treads_desert_born", new SpellMeta("Desert Born", 1));
        meta.put("megamod:relic_sandwalker_treads_quicksand", new SpellMeta("Quicksand", 4));
        meta.put("megamod:relic_sandwalker_treads_sandstorm", new SpellMeta("Sandstorm", 7));
        meta.put("megamod:relic_stormstrider_boots_lightning_step", new SpellMeta("Lightning Step", 1));
        meta.put("megamod:relic_stormstrider_boots_thunder_leap", new SpellMeta("Thunder Leap", 5));
        meta.put("megamod:relic_chrono_glove_temporal_flux", new SpellMeta("Temporal Flux", 1));
        meta.put("megamod:relic_chrono_glove_time_snap", new SpellMeta("Time Snap", 5));
        meta.put("megamod:relic_chrono_glove_stasis_field", new SpellMeta("Stasis Field", 8));
        meta.put("megamod:relic_ender_hand_enderman_peace", new SpellMeta("Enderman Peace", 1));
        meta.put("megamod:relic_ender_hand_teleport_swap", new SpellMeta("Teleport Swap", 3));
        meta.put("megamod:relic_rage_glove_fury", new SpellMeta("Fury", 1));
        meta.put("megamod:relic_rage_glove_bare_knuckle", new SpellMeta("Bare Knuckle", 4));
        meta.put("megamod:relic_rage_glove_berserk", new SpellMeta("Berserk", 7));
        meta.put("megamod:relic_thornweave_glove_thorned_grasp", new SpellMeta("Thorned Grasp", 1));
        meta.put("megamod:relic_thornweave_glove_vine_lash", new SpellMeta("Vine Lash", 4));
        meta.put("megamod:relic_thornweave_glove_entangle", new SpellMeta("Entangle", 7));
        meta.put("megamod:relic_wool_mitten_warmth", new SpellMeta("Warmth", 1));
        meta.put("megamod:relic_wool_mitten_comfort", new SpellMeta("Comfort", 3));
        meta.put("megamod:relic_wool_mitten_cozy", new SpellMeta("Cozy", 5));
        meta.put("megamod:relic_arcane_gauntlet_mana_shield", new SpellMeta("Mana Shield", 1));
        meta.put("megamod:relic_arcane_gauntlet_arcane_bolt", new SpellMeta("Arcane Bolt", 3));
        meta.put("megamod:relic_arcane_gauntlet_spellweave", new SpellMeta("Spellweave", 7));
        meta.put("megamod:relic_iron_fist_heavy_blows", new SpellMeta("Heavy Blows", 1));
        meta.put("megamod:relic_iron_fist_uppercut", new SpellMeta("Uppercut", 4));
        meta.put("megamod:relic_iron_fist_ground_pound", new SpellMeta("Ground Pound", 7));
        meta.put("megamod:relic_plague_grasp_venomous_touch", new SpellMeta("Venomous Touch", 1));
        meta.put("megamod:relic_plague_grasp_wither_grip", new SpellMeta("Wither Grip", 4));
        meta.put("megamod:relic_plague_grasp_plague_wave", new SpellMeta("Plague Wave", 7));
        meta.put("megamod:relic_sunforged_bracer_blessed_strikes", new SpellMeta("Blessed Strikes", 1));
        meta.put("megamod:relic_sunforged_bracer_purifying_touch", new SpellMeta("Purifying Touch", 5));
        meta.put("megamod:relic_sunforged_bracer_divine_smite", new SpellMeta("Divine Smite", 7));
        meta.put("megamod:relic_ashen_diadem_ember_sight", new SpellMeta("Ember Sight", 1));
        meta.put("megamod:relic_ashen_diadem_infernal_command", new SpellMeta("Infernal Command", 4));
        meta.put("megamod:relic_ashen_diadem_pyroclasm", new SpellMeta("Pyroclasm", 7));
        meta.put("megamod:relic_lunar_crown_lunar_glow", new SpellMeta("Lunar Glow", 1));
        meta.put("megamod:relic_lunar_crown_moonbeam", new SpellMeta("Moonbeam", 3));
        meta.put("megamod:relic_lunar_crown_eclipse", new SpellMeta("Eclipse", 7));
        meta.put("megamod:relic_solar_crown_solar_warmth", new SpellMeta("Solar Warmth", 1));
        meta.put("megamod:relic_solar_crown_sunfire", new SpellMeta("Sunfire", 3));
        meta.put("megamod:relic_solar_crown_radiance", new SpellMeta("Radiance", 7));
        meta.put("megamod:relic_stormcaller_circlet_static_field", new SpellMeta("Static Field", 1));
        meta.put("megamod:relic_stormcaller_circlet_thunder_strike", new SpellMeta("Thunder Strike", 4));
        meta.put("megamod:relic_stormcaller_circlet_tempest_aura", new SpellMeta("Tempest Aura", 7));
        meta.put("megamod:relic_wraith_crown_ethereal_sight", new SpellMeta("Ethereal Sight", 1));
        meta.put("megamod:relic_wraith_crown_soul_siphon", new SpellMeta("Soul Siphon", 4));
        meta.put("megamod:relic_wraith_crown_phantom_form", new SpellMeta("Phantom Form", 7));
        meta.put("megamod:relic_bloodstone_choker_bloodlust", new SpellMeta("Bloodlust", 1));
        meta.put("megamod:relic_bloodstone_choker_blood_price", new SpellMeta("Blood Price", 4));
        meta.put("megamod:relic_bloodstone_choker_sanguine_feast", new SpellMeta("Sanguine Feast", 7));
        meta.put("megamod:relic_frostfire_pendant_equilibrium", new SpellMeta("Equilibrium", 1));
        meta.put("megamod:relic_frostfire_pendant_frostfire_bolt", new SpellMeta("Frostfire Bolt", 4));
        meta.put("megamod:relic_frostfire_pendant_elemental_storm", new SpellMeta("Elemental Storm", 7));
        meta.put("megamod:relic_holy_locket_steal", new SpellMeta("Steal", 1));
        meta.put("megamod:relic_holy_locket_purify", new SpellMeta("Purify", 4));
        meta.put("megamod:relic_holy_locket_sanctify", new SpellMeta("Sanctify", 7));
        meta.put("megamod:relic_jellyfish_necklace_unsinkable", new SpellMeta("Unsinkable", 1));
        meta.put("megamod:relic_jellyfish_necklace_shock", new SpellMeta("Shock", 3));
        meta.put("megamod:relic_jellyfish_necklace_paralysis", new SpellMeta("Paralysis", 6));
        meta.put("megamod:relic_reflection_necklace_absorb", new SpellMeta("Absorb", 1));
        meta.put("megamod:relic_reflection_necklace_explode", new SpellMeta("Explode", 3));
        meta.put("megamod:relic_tidekeeper_amulet_aquatic_grace", new SpellMeta("Aquatic Grace", 1));
        meta.put("megamod:relic_tidekeeper_amulet_tidal_wave", new SpellMeta("Tidal Wave", 4));
        meta.put("megamod:relic_tidekeeper_amulet_whirlpool", new SpellMeta("Whirlpool", 7));
        meta.put("megamod:relic_bastion_ring_piglin_peace", new SpellMeta("Piglin Peace", 1));
        meta.put("megamod:relic_bastion_ring_barter_bonus", new SpellMeta("Barter Bonus", 3));
        meta.put("megamod:relic_bastion_ring_gilded_strike", new SpellMeta("Gilded Strike", 5));
        meta.put("megamod:relic_chorus_inhibitor_anchor", new SpellMeta("Anchor", 1));
        meta.put("megamod:relic_chorus_inhibitor_displace", new SpellMeta("Displace", 4));
        meta.put("megamod:relic_chorus_inhibitor_void_grip", new SpellMeta("Void Grip", 6));
        meta.put("megamod:relic_emberstone_band_warm_aura", new SpellMeta("Warm Aura", 1));
        meta.put("megamod:relic_emberstone_band_fire_snap", new SpellMeta("Fire Snap", 3));
        meta.put("megamod:relic_emberstone_band_combustion", new SpellMeta("Combustion", 6));
        meta.put("megamod:relic_gravestone_ring_death_ward", new SpellMeta("Death Ward", 1));
        meta.put("megamod:relic_gravestone_ring_life_tap", new SpellMeta("Life Tap", 4));
        meta.put("megamod:relic_gravestone_ring_undying_resolve", new SpellMeta("Undying Resolve", 7));
        meta.put("megamod:relic_stormband_charged_steps", new SpellMeta("Charged Steps", 1));
        meta.put("megamod:relic_stormband_arc_discharge", new SpellMeta("Arc Discharge", 4));
        meta.put("megamod:relic_stormband_galvanic_surge", new SpellMeta("Galvanic Surge", 7));
        meta.put("megamod:relic_verdant_signet_nature_s_blessing", new SpellMeta("Nature's Blessing", 1));
        meta.put("megamod:relic_verdant_signet_growth_surge", new SpellMeta("Growth Surge", 4));
        meta.put("megamod:relic_verdant_signet_bloom_shield", new SpellMeta("Bloom Shield", 7));
        meta.put("megamod:relic_blazing_flask_fire_ball", new SpellMeta("Fire Ball", 1));
        meta.put("megamod:relic_blazing_flask_jetpack", new SpellMeta("Jetpack", 5));
        meta.put("megamod:relic_horse_flute_store", new SpellMeta("Store", 1));
        meta.put("megamod:relic_horse_flute_release", new SpellMeta("Release", 1));
        meta.put("megamod:relic_infinity_ham_feast", new SpellMeta("Feast", 1));
        meta.put("megamod:relic_infinity_ham_alchemy", new SpellMeta("Alchemy", 4));
        meta.put("megamod:relic_magic_mirror_recall", new SpellMeta("Recall", 1));
        meta.put("megamod:relic_magic_mirror_bed_recall", new SpellMeta("Bed Recall", 5));
        meta.put("megamod:relic_mending_chalice_healing_draught", new SpellMeta("Healing Draught", 1));
        meta.put("megamod:relic_mending_chalice_sanctified_ground", new SpellMeta("Sanctified Ground", 5));
        meta.put("megamod:relic_shadow_glaive_throw", new SpellMeta("Throw", 1));
        meta.put("megamod:relic_shadow_glaive_saw_mode", new SpellMeta("Saw Mode", 5));
        meta.put("megamod:relic_space_dissector_mark", new SpellMeta("Mark", 1));
        meta.put("megamod:relic_space_dissector_warp", new SpellMeta("Warp", 3));
        meta.put("megamod:relic_spore_sack_spore_shot", new SpellMeta("Spore Shot", 1));
        meta.put("megamod:relic_spore_sack_cloud", new SpellMeta("Cloud", 5));
        meta.put("megamod:relic_thunderhorn_war_cry", new SpellMeta("War Cry", 1));
        meta.put("megamod:relic_thunderhorn_sonic_boom", new SpellMeta("Sonic Boom", 5));
        meta.put("megamod:relic_void_lantern_dark_beacon", new SpellMeta("Dark Beacon", 1));
        meta.put("megamod:relic_void_lantern_dimensional_tear", new SpellMeta("Dimensional Tear", 5));
        META = Map.copyOf(meta);
    }

    public static List<String> forItem(String itemId) {
        return SPELLS.getOrDefault(itemId, List.of());
    }

    public static SpellMeta metaFor(String spellId) {
        return META.get(spellId);
    }
}
