modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "skill_tree_rpgs"
version = "${version}"
displayName = "Skill Tree (RPG Series)"
authors = "Daedelus"
description = '''
Specialise your RPG class, by unlocking powerful skills.
'''
logoFile = "assets/skill_tree_rpgs/icon.png"

[[dependencies.skill_tree_rpgs]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skill_tree_rpgs]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_compat_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skill_tree_rpgs]]
modId = "spell_engine"
type = "required"
versionRange = "[${spell_engine_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skill_tree_rpgs]]
modId = "spell_power"
type = "required"
versionRange = "[${spell_power_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.skill_tree_rpgs]]
modId = "puffish_skills"
type = "required"
versionRange = "[${pufferfish_skills_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "skill_tree_rpgs.mixins.json"
