modLoader = "javafml"
loaderVersion = "[4,)"
license = "All Rights Reserved"

[[mods]]
modId = "arsenal"
version = "${version}"
displayName = "Arsenal (RPG Series)"
authors = "Daedelus"
description = '''
Legendary weapons from the past - not crafted, but conquered.
'''
logoFile = "icon.png"

[[dependencies.arsenal]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arsenal]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_compat_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arsenal]]
modId = "spell_engine"
type = "required"
versionRange = "[${spell_engine_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.arsenal]]
modId = "ranged_weapon_api"
type = "required"
versionRange = "[${ranged_weapon_api_version},)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "arsenal.mixins.json"
