/*
 * Decompiled with CFR 0.152.
 */
package com.ultra.megamod.feature.museum.catalog;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

public class ItemCatalog {
    public static final String[] CATEGORIES = new String[]{"Minerals & Ores", "Tools & Utilities", "Combat", "Armor", "Food & Drinks", "Potions & Brewing", "Building Blocks", "Natural Blocks", "Flowers & Plants", "Decoration", "Redstone", "Transportation", "Crafting Materials", "Music Discs", "Banner Patterns & Dyes", "Spawn Eggs & Miscellaneous", "Dungeon Loot", "Relics & Artifacts"};
    public static final Map<String, List<String>> ITEMS_BY_CATEGORY = new LinkedHashMap<String, List<String>>();

    public static int getTotalItemCount() {
        java.util.HashSet<String> unique = new java.util.HashSet<>();
        for (List<String> items : ITEMS_BY_CATEGORY.values()) {
            unique.addAll(items);
        }
        return unique.size();
    }

    public static List<String> getItemsInCategory(String category) {
        return ITEMS_BY_CATEGORY.getOrDefault(category, List.of());
    }

    public static String getCategoryForItem(String itemId) {
        for (Map.Entry<String, List<String>> entry : ITEMS_BY_CATEGORY.entrySet()) {
            if (!entry.getValue().contains(itemId)) continue;
            return entry.getKey();
        }
        return null;
    }

    public static boolean contains(String itemId) {
        return ItemCatalog.getCategoryForItem(itemId) != null;
    }

    public static int getCategoryCount() {
        return CATEGORIES.length;
    }

    static {
        ITEMS_BY_CATEGORY.put("Minerals & Ores", List.of("minecraft:coal", "minecraft:charcoal", "minecraft:raw_iron", "minecraft:raw_gold", "minecraft:raw_copper", "minecraft:iron_ingot", "minecraft:gold_ingot", "minecraft:iron_nugget", "minecraft:gold_nugget", "minecraft:diamond", "minecraft:emerald", "minecraft:lapis_lazuli", "minecraft:netherite_ingot", "minecraft:netherite_scrap", "minecraft:ancient_debris", "minecraft:amethyst_shard", "minecraft:quartz", "minecraft:glowstone_dust", "minecraft:flint", "minecraft:coal_ore", "minecraft:iron_ore", "minecraft:gold_ore", "minecraft:copper_ore", "minecraft:diamond_ore", "minecraft:emerald_ore", "minecraft:lapis_ore", "minecraft:redstone_ore", "minecraft:nether_gold_ore", "minecraft:nether_quartz_ore", "minecraft:deepslate_coal_ore", "minecraft:deepslate_iron_ore", "minecraft:deepslate_gold_ore", "minecraft:deepslate_copper_ore", "minecraft:deepslate_diamond_ore", "minecraft:deepslate_emerald_ore", "minecraft:deepslate_lapis_ore", "minecraft:deepslate_redstone_ore"));
        ITEMS_BY_CATEGORY.put("Tools & Utilities", List.of("minecraft:wooden_pickaxe", "minecraft:stone_pickaxe", "minecraft:iron_pickaxe", "minecraft:golden_pickaxe", "minecraft:diamond_pickaxe", "minecraft:netherite_pickaxe", "minecraft:wooden_axe", "minecraft:stone_axe", "minecraft:iron_axe", "minecraft:golden_axe", "minecraft:diamond_axe", "minecraft:netherite_axe", "minecraft:wooden_shovel", "minecraft:stone_shovel", "minecraft:iron_shovel", "minecraft:golden_shovel", "minecraft:diamond_shovel", "minecraft:netherite_shovel", "minecraft:wooden_hoe", "minecraft:stone_hoe", "minecraft:iron_hoe", "minecraft:golden_hoe", "minecraft:diamond_hoe", "minecraft:netherite_hoe", "minecraft:shears", "minecraft:flint_and_steel", "minecraft:fishing_rod", "minecraft:compass", "minecraft:recovery_compass", "minecraft:clock", "minecraft:spyglass", "minecraft:brush", "minecraft:lead", "minecraft:name_tag", "minecraft:bucket", "minecraft:water_bucket", "minecraft:lava_bucket", "minecraft:powder_snow_bucket", "minecraft:milk_bucket", "minecraft:axolotl_bucket", "minecraft:cod_bucket", "minecraft:salmon_bucket", "minecraft:tropical_fish_bucket", "minecraft:pufferfish_bucket", "minecraft:tadpole_bucket", "minecraft:writable_book", "minecraft:written_book", "minecraft:map", "minecraft:filled_map", "minecraft:bundle", "minecraft:ender_eye"));
        ITEMS_BY_CATEGORY.put("Combat", List.of("minecraft:wooden_sword", "minecraft:stone_sword", "minecraft:iron_sword", "minecraft:golden_sword", "minecraft:diamond_sword", "minecraft:netherite_sword", "minecraft:bow", "minecraft:crossbow", "minecraft:trident", "minecraft:mace", "minecraft:shield", "minecraft:arrow", "minecraft:spectral_arrow", "minecraft:tipped_arrow", "minecraft:totem_of_undying", "minecraft:ender_pearl", "minecraft:wind_charge", "minecraft:fire_charge", "minecraft:snowball", "minecraft:egg", "minecraft:tnt"));
        ITEMS_BY_CATEGORY.put("Armor", List.of("minecraft:leather_helmet", "minecraft:leather_chestplate", "minecraft:leather_leggings", "minecraft:leather_boots", "minecraft:chainmail_helmet", "minecraft:chainmail_chestplate", "minecraft:chainmail_leggings", "minecraft:chainmail_boots", "minecraft:iron_helmet", "minecraft:iron_chestplate", "minecraft:iron_leggings", "minecraft:iron_boots", "minecraft:golden_helmet", "minecraft:golden_chestplate", "minecraft:golden_leggings", "minecraft:golden_boots", "minecraft:diamond_helmet", "minecraft:diamond_chestplate", "minecraft:diamond_leggings", "minecraft:diamond_boots", "minecraft:netherite_helmet", "minecraft:netherite_chestplate", "minecraft:netherite_leggings", "minecraft:netherite_boots", "minecraft:turtle_helmet", "minecraft:elytra", "minecraft:wolf_armor"));
        ITEMS_BY_CATEGORY.put("Food & Drinks", List.of("minecraft:apple", "minecraft:golden_apple", "minecraft:enchanted_golden_apple", "minecraft:bread", "minecraft:beef", "minecraft:cooked_beef", "minecraft:porkchop", "minecraft:cooked_porkchop", "minecraft:chicken", "minecraft:cooked_chicken", "minecraft:mutton", "minecraft:cooked_mutton", "minecraft:rabbit", "minecraft:cooked_rabbit", "minecraft:cod", "minecraft:cooked_cod", "minecraft:salmon", "minecraft:cooked_salmon", "minecraft:tropical_fish", "minecraft:pufferfish", "minecraft:golden_carrot", "minecraft:carrot", "minecraft:potato", "minecraft:baked_potato", "minecraft:poisonous_potato", "minecraft:beetroot", "minecraft:pumpkin_pie", "minecraft:cake", "minecraft:cookie", "minecraft:melon_slice", "minecraft:sweet_berries", "minecraft:glow_berries", "minecraft:honey_bottle", "minecraft:mushroom_stew", "minecraft:beetroot_soup", "minecraft:rabbit_stew", "minecraft:suspicious_stew", "minecraft:dried_kelp", "minecraft:chorus_fruit", "minecraft:rotten_flesh", "minecraft:spider_eye", "minecraft:ominous_bottle"));
        ITEMS_BY_CATEGORY.put("Potions & Brewing", List.of("minecraft:potion", "minecraft:splash_potion", "minecraft:lingering_potion", "minecraft:glass_bottle", "minecraft:dragon_breath", "minecraft:brewing_stand", "minecraft:cauldron", "minecraft:blaze_powder", "minecraft:blaze_rod", "minecraft:nether_wart", "minecraft:ghast_tear", "minecraft:magma_cream", "minecraft:fermented_spider_eye", "minecraft:glistering_melon_slice", "minecraft:rabbit_foot", "minecraft:phantom_membrane", "minecraft:turtle_scute", "minecraft:breeze_rod"));
        ITEMS_BY_CATEGORY.put("Building Blocks", List.of("minecraft:oak_planks", "minecraft:spruce_planks", "minecraft:birch_planks", "minecraft:jungle_planks", "minecraft:acacia_planks", "minecraft:dark_oak_planks", "minecraft:mangrove_planks", "minecraft:cherry_planks", "minecraft:bamboo_planks", "minecraft:crimson_planks", "minecraft:warped_planks", "minecraft:oak_log", "minecraft:spruce_log", "minecraft:birch_log", "minecraft:jungle_log", "minecraft:acacia_log", "minecraft:dark_oak_log", "minecraft:mangrove_log", "minecraft:cherry_log", "minecraft:bamboo_block", "minecraft:crimson_stem", "minecraft:warped_stem", "minecraft:cobblestone", "minecraft:stone", "minecraft:smooth_stone", "minecraft:stone_bricks", "minecraft:mossy_stone_bricks", "minecraft:cracked_stone_bricks", "minecraft:chiseled_stone_bricks", "minecraft:deepslate", "minecraft:cobbled_deepslate", "minecraft:polished_deepslate", "minecraft:deepslate_bricks", "minecraft:deepslate_tiles", "minecraft:chiseled_deepslate", "minecraft:bricks", "minecraft:sandstone", "minecraft:chiseled_sandstone", "minecraft:smooth_sandstone", "minecraft:red_sandstone", "minecraft:chiseled_red_sandstone", "minecraft:smooth_red_sandstone", "minecraft:prismarine", "minecraft:prismarine_bricks", "minecraft:dark_prismarine", "minecraft:obsidian", "minecraft:crying_obsidian", "minecraft:purpur_block", "minecraft:purpur_pillar", "minecraft:end_stone", "minecraft:end_stone_bricks", "minecraft:quartz_block", "minecraft:chiseled_quartz_block", "minecraft:smooth_quartz", "minecraft:quartz_bricks", "minecraft:quartz_pillar", "minecraft:nether_bricks", "minecraft:red_nether_bricks", "minecraft:chiseled_nether_bricks", "minecraft:blackstone", "minecraft:polished_blackstone", "minecraft:polished_blackstone_bricks", "minecraft:chiseled_polished_blackstone", "minecraft:gilded_blackstone", "minecraft:basalt", "minecraft:polished_basalt", "minecraft:smooth_basalt", "minecraft:tuff", "minecraft:polished_tuff", "minecraft:tuff_bricks", "minecraft:chiseled_tuff_bricks", "minecraft:chiseled_tuff", "minecraft:calcite", "minecraft:dripstone_block", "minecraft:mud_bricks", "minecraft:packed_mud", "minecraft:reinforced_deepslate", "minecraft:amethyst_block", "minecraft:copper_block", "minecraft:exposed_copper", "minecraft:weathered_copper", "minecraft:oxidized_copper", "minecraft:cut_copper", "minecraft:chiseled_copper", "minecraft:copper_grate", "minecraft:copper_bulb"));
        ITEMS_BY_CATEGORY.put("Natural Blocks", List.of("minecraft:dirt", "minecraft:grass_block", "minecraft:podzol", "minecraft:mycelium", "minecraft:mud", "minecraft:clay", "minecraft:gravel", "minecraft:sand", "minecraft:red_sand", "minecraft:soul_sand", "minecraft:soul_soil", "minecraft:netherrack", "minecraft:magma_block", "minecraft:glowstone", "minecraft:ice", "minecraft:packed_ice", "minecraft:blue_ice", "minecraft:snow_block", "minecraft:powder_snow", "minecraft:moss_block", "minecraft:moss_carpet", "minecraft:sculk", "minecraft:sculk_catalyst", "minecraft:sculk_sensor", "minecraft:calibrated_sculk_sensor", "minecraft:sculk_shrieker", "minecraft:sculk_vein", "minecraft:pointed_dripstone", "minecraft:oak_leaves", "minecraft:spruce_leaves", "minecraft:birch_leaves", "minecraft:jungle_leaves", "minecraft:acacia_leaves", "minecraft:dark_oak_leaves", "minecraft:mangrove_leaves", "minecraft:cherry_leaves", "minecraft:azalea_leaves", "minecraft:flowering_azalea_leaves", "minecraft:nether_wart_block", "minecraft:warped_wart_block", "minecraft:shroomlight", "minecraft:crimson_nylium", "minecraft:warped_nylium", "minecraft:hay_block", "minecraft:bone_block", "minecraft:honeycomb_block", "minecraft:honey_block", "minecraft:sponge", "minecraft:wet_sponge", "minecraft:cobweb", "minecraft:bedrock"));
        ITEMS_BY_CATEGORY.put("Flowers & Plants", List.of("minecraft:dandelion", "minecraft:poppy", "minecraft:blue_orchid", "minecraft:allium", "minecraft:azure_bluet", "minecraft:red_tulip", "minecraft:orange_tulip", "minecraft:white_tulip", "minecraft:pink_tulip", "minecraft:oxeye_daisy", "minecraft:cornflower", "minecraft:lily_of_the_valley", "minecraft:wither_rose", "minecraft:torchflower", "minecraft:pitcher_plant", "minecraft:sunflower", "minecraft:lilac", "minecraft:rose_bush", "minecraft:peony", "minecraft:oak_sapling", "minecraft:spruce_sapling", "minecraft:birch_sapling", "minecraft:jungle_sapling", "minecraft:acacia_sapling", "minecraft:dark_oak_sapling", "minecraft:cherry_sapling", "minecraft:mangrove_propagule", "minecraft:azalea", "minecraft:flowering_azalea", "minecraft:dead_bush", "minecraft:lily_pad", "minecraft:kelp", "minecraft:seagrass", "minecraft:sea_pickle", "minecraft:glow_lichen", "minecraft:spore_blossom", "minecraft:small_dripleaf", "minecraft:big_dripleaf", "minecraft:hanging_roots", "minecraft:vine", "minecraft:cave_vines", "minecraft:twisting_vines", "minecraft:weeping_vines", "minecraft:crimson_roots", "minecraft:warped_roots", "minecraft:nether_sprouts", "minecraft:crimson_fungus", "minecraft:warped_fungus", "minecraft:short_grass", "minecraft:tall_grass", "minecraft:fern", "minecraft:large_fern"));
        ITEMS_BY_CATEGORY.put("Decoration", List.of("minecraft:torch", "minecraft:soul_torch", "minecraft:lantern", "minecraft:soul_lantern", "minecraft:candle", "minecraft:sea_lantern", "minecraft:end_rod", "minecraft:chain", "minecraft:iron_bars", "minecraft:glass", "minecraft:glass_pane", "minecraft:tinted_glass", "minecraft:flower_pot", "minecraft:painting", "minecraft:item_frame", "minecraft:glow_item_frame", "minecraft:armor_stand", "minecraft:bell", "minecraft:campfire", "minecraft:soul_campfire", "minecraft:bookshelf", "minecraft:chiseled_bookshelf", "minecraft:lectern", "minecraft:decorated_pot", "minecraft:banner", "minecraft:skeleton_skull", "minecraft:wither_skeleton_skull", "minecraft:zombie_head", "minecraft:creeper_head", "minecraft:dragon_head", "minecraft:piglin_head", "minecraft:anvil", "minecraft:grindstone", "minecraft:stonecutter", "minecraft:loom", "minecraft:cartography_table", "minecraft:smithing_table", "minecraft:fletching_table", "minecraft:crafting_table", "minecraft:furnace", "minecraft:blast_furnace", "minecraft:smoker", "minecraft:enchanting_table", "minecraft:conduit", "minecraft:beacon", "minecraft:respawn_anchor", "minecraft:lodestone", "minecraft:lightning_rod", "minecraft:bed", "minecraft:trial_spawner", "minecraft:vault"));
        ITEMS_BY_CATEGORY.put("Redstone", List.of("minecraft:redstone", "minecraft:redstone_block", "minecraft:redstone_torch", "minecraft:redstone_lamp", "minecraft:repeater", "minecraft:comparator", "minecraft:piston", "minecraft:sticky_piston", "minecraft:observer", "minecraft:dropper", "minecraft:dispenser", "minecraft:hopper", "minecraft:lever", "minecraft:stone_button", "minecraft:oak_button", "minecraft:stone_pressure_plate", "minecraft:oak_pressure_plate", "minecraft:light_weighted_pressure_plate", "minecraft:heavy_weighted_pressure_plate", "minecraft:tripwire_hook", "minecraft:trapped_chest", "minecraft:daylight_detector", "minecraft:note_block", "minecraft:jukebox", "minecraft:target", "minecraft:crafter", "minecraft:copper_trapdoor", "minecraft:copper_door"));
        ITEMS_BY_CATEGORY.put("Transportation", List.of("minecraft:oak_boat", "minecraft:spruce_boat", "minecraft:birch_boat", "minecraft:jungle_boat", "minecraft:acacia_boat", "minecraft:dark_oak_boat", "minecraft:mangrove_boat", "minecraft:cherry_boat", "minecraft:bamboo_raft", "minecraft:oak_chest_boat", "minecraft:spruce_chest_boat", "minecraft:birch_chest_boat", "minecraft:jungle_chest_boat", "minecraft:acacia_chest_boat", "minecraft:dark_oak_chest_boat", "minecraft:mangrove_chest_boat", "minecraft:cherry_chest_boat", "minecraft:bamboo_chest_raft", "minecraft:minecart", "minecraft:chest_minecart", "minecraft:furnace_minecart", "minecraft:tnt_minecart", "minecraft:hopper_minecart", "minecraft:rail", "minecraft:powered_rail", "minecraft:detector_rail", "minecraft:activator_rail", "minecraft:saddle", "minecraft:leather_horse_armor", "minecraft:iron_horse_armor", "minecraft:golden_horse_armor", "minecraft:diamond_horse_armor", "minecraft:carrot_on_a_stick", "minecraft:warped_fungus_on_a_stick"));
        ITEMS_BY_CATEGORY.put("Crafting Materials", List.of("minecraft:stick", "minecraft:string", "minecraft:feather", "minecraft:leather", "minecraft:rabbit_hide", "minecraft:bone", "minecraft:bone_meal", "minecraft:ink_sac", "minecraft:glow_ink_sac", "minecraft:slime_ball", "minecraft:gunpowder", "minecraft:sugar", "minecraft:sugar_cane", "minecraft:wheat", "minecraft:wheat_seeds", "minecraft:beetroot_seeds", "minecraft:pumpkin_seeds", "minecraft:melon_seeds", "minecraft:torchflower_seeds", "minecraft:pitcher_pod", "minecraft:cocoa_beans", "minecraft:cactus", "minecraft:bamboo", "minecraft:kelp", "minecraft:nether_star", "minecraft:eye_of_ender", "minecraft:heart_of_the_sea", "minecraft:nautilus_shell", "minecraft:prismarine_shard", "minecraft:prismarine_crystals", "minecraft:shulker_shell", "minecraft:echo_shard", "minecraft:disc_fragment_5", "minecraft:honeycomb", "minecraft:paper", "minecraft:book", "minecraft:experience_bottle", "minecraft:clay_ball", "minecraft:brick", "minecraft:nether_brick", "minecraft:copper_ingot", "minecraft:trial_key", "minecraft:ominous_trial_key", "minecraft:armadillo_scute"));
        ITEMS_BY_CATEGORY.put("Music Discs", List.of("minecraft:music_disc_13", "minecraft:music_disc_cat", "minecraft:music_disc_blocks", "minecraft:music_disc_chirp", "minecraft:music_disc_far", "minecraft:music_disc_mall", "minecraft:music_disc_mellohi", "minecraft:music_disc_stal", "minecraft:music_disc_strad", "minecraft:music_disc_ward", "minecraft:music_disc_11", "minecraft:music_disc_wait", "minecraft:music_disc_otherside", "minecraft:music_disc_5", "minecraft:music_disc_pigstep", "minecraft:music_disc_relic", "minecraft:music_disc_precipice", "minecraft:music_disc_creator", "minecraft:music_disc_creator_music_box"));
        ITEMS_BY_CATEGORY.put("Banner Patterns & Dyes", List.of("minecraft:white_dye", "minecraft:orange_dye", "minecraft:magenta_dye", "minecraft:light_blue_dye", "minecraft:yellow_dye", "minecraft:lime_dye", "minecraft:pink_dye", "minecraft:gray_dye", "minecraft:light_gray_dye", "minecraft:cyan_dye", "minecraft:purple_dye", "minecraft:blue_dye", "minecraft:brown_dye", "minecraft:green_dye", "minecraft:red_dye", "minecraft:black_dye", "minecraft:flower_banner_pattern", "minecraft:creeper_banner_pattern", "minecraft:skull_banner_pattern", "minecraft:mojang_banner_pattern", "minecraft:globe_banner_pattern", "minecraft:piglin_banner_pattern", "minecraft:flow_banner_pattern", "minecraft:guster_banner_pattern"));
        ITEMS_BY_CATEGORY.put("Spawn Eggs & Miscellaneous", List.of("minecraft:chest", "minecraft:ender_chest", "minecraft:barrel", "minecraft:shulker_box", "minecraft:enchanted_book", "minecraft:knowledge_book", "minecraft:command_block", "minecraft:structure_block", "minecraft:dragon_egg", "minecraft:end_crystal", "minecraft:chorus_flower", "minecraft:chorus_plant", "minecraft:froglight", "minecraft:ochre_froglight", "minecraft:verdant_froglight", "minecraft:pearlescent_froglight", "minecraft:sniffer_egg", "minecraft:turtle_egg", "minecraft:goat_horn", "minecraft:pottery_sherd", "minecraft:netherite_upgrade_smithing_template", "minecraft:sentry_armor_trim_smithing_template", "minecraft:coast_armor_trim_smithing_template", "minecraft:dune_armor_trim_smithing_template", "minecraft:eye_armor_trim_smithing_template", "minecraft:host_armor_trim_smithing_template", "minecraft:raiser_armor_trim_smithing_template", "minecraft:rib_armor_trim_smithing_template", "minecraft:shaper_armor_trim_smithing_template", "minecraft:silence_armor_trim_smithing_template", "minecraft:snout_armor_trim_smithing_template", "minecraft:spire_armor_trim_smithing_template", "minecraft:tide_armor_trim_smithing_template", "minecraft:vex_armor_trim_smithing_template", "minecraft:ward_armor_trim_smithing_template", "minecraft:wayfinder_armor_trim_smithing_template", "minecraft:wild_armor_trim_smithing_template", "minecraft:bolt_armor_trim_smithing_template", "minecraft:flow_armor_trim_smithing_template", "minecraft:heavy_core"));
        ITEMS_BY_CATEGORY.put("Dungeon Loot", List.of("megamod:void_shard", "megamod:cerulean_ingot", "megamod:crystalline_shard", "megamod:spectral_silk", "megamod:umbra_ingot", "megamod:naga_fang_dagger", "megamod:wrought_axe", "megamod:wrought_helm", "megamod:ice_crystal", "megamod:spear", "megamod:life_stealer", "megamod:scepter_of_chaos", "megamod:sol_visage", "megamod:earthrend_gauntlet", "megamod:blowgun", "megamod:ossukage_sword", "megamod:geomancer_helm", "megamod:geomancer_chest", "megamod:geomancer_legs", "megamod:geomancer_boots", "megamod:mask_of_fear", "megamod:mask_of_fury", "megamod:mask_of_faith", "megamod:mask_of_rage", "megamod:mask_of_misery", "megamod:mask_of_bliss", "megamod:wraith_trophy", "megamod:ossukage_trophy", "megamod:dungeon_keeper_trophy", "megamod:frostmaw_trophy", "megamod:wroughtnaut_trophy", "megamod:umvuthi_trophy", "megamod:chaos_spawner_trophy", "megamod:sculptor_trophy", "megamod:glowing_jelly", "megamod:strange_meat", "megamod:great_experience_bottle", "megamod:absorption_orb", "megamod:soul_anchor", "megamod:dungeon_map", "megamod:infernal_essence", "megamod:warp_stone", "megamod:living_divining_rod", "megamod:cerulean_arrow", "megamod:crystal_arrow", "megamod:dart_ammo", "megamod:rat_fang", "megamod:fang_on_a_stick", "megamod:skeleton_bone", "megamod:skeleton_head", "megamod:captured_grottol", "megamod:foliaath_seed", "megamod:bluff_rod"));
        ITEMS_BY_CATEGORY.put("Relics & Artifacts", List.of("megamod:arrow_quiver", "megamod:elytra_booster", "megamod:midnight_robe", "megamod:leather_belt", "megamod:drowned_belt", "megamod:hunter_belt", "megamod:ender_hand", "megamod:rage_glove", "megamod:wool_mitten", "megamod:magma_walker", "megamod:aqua_walker", "megamod:ice_skates", "megamod:ice_breaker", "megamod:roller_skates", "megamod:amphibian_boot", "megamod:reflection_necklace", "megamod:jellyfish_necklace", "megamod:holy_locket", "megamod:bastion_ring", "megamod:chorus_inhibitor", "megamod:shadow_glaive", "megamod:infinity_ham", "megamod:space_dissector", "megamod:magic_mirror", "megamod:horse_flute", "megamod:spore_sack", "megamod:blazing_flask", "megamod:lunar_crown", "megamod:solar_crown"));
    }
}

